hotkey-context =
    .player = Joueur
    .spectator = Spectateur
    .chat-input = Saisie du Chat
    .menu = Menu
    .editor = Éditeur

## chat.yaml
hotkey-description-openteamchat = Chat d'Équipe
hotkey-description-opengeneralchat = Chat Général
hotkey-description-togglechatmode = Basculer Mode Chat
hotkey-description-autocomplete = Autocomplétion

## control-groups.yaml
hotkey-description-controlgroupselect01 = Sélectionner groupe 1
hotkey-description-controlgroupselect02 = Sélectionner groupe 2
hotkey-description-controlgroupselect03 = Sélectionner groupe 3
hotkey-description-controlgroupselect04 = Sélectionner groupe 4
hotkey-description-controlgroupselect05 = Sélectionner groupe 5
hotkey-description-controlgroupselect06 = Sélectionner groupe 6
hotkey-description-controlgroupselect07 = Sélectionner groupe 7
hotkey-description-controlgroupselect08 = Sélectionner groupe 8
hotkey-description-controlgroupselect09 = Sélectionner groupe 9
hotkey-description-controlgroupselect10 = Sélectionner groupe 0
hotkey-description-controlgroupcreate01 = Créer groupe 1
hotkey-description-controlgroupcreate02 = Créer groupe 2
hotkey-description-controlgroupcreate03 = Créer groupe 3
hotkey-description-controlgroupcreate04 = Créer groupe 4
hotkey-description-controlgroupcreate05 = Créer groupe 5
hotkey-description-controlgroupcreate06 = Créer groupe 6
hotkey-description-controlgroupcreate07 = Créer groupe 7
hotkey-description-controlgroupcreate08 = Créer groupe 8
hotkey-description-controlgroupcreate09 = Créer groupe 9
hotkey-description-controlgroupcreate10 = Créer groupe 0
hotkey-description-controlgroupaddto01 = Ajouter au groupe 1
hotkey-description-controlgroupaddto02 = Ajouter au groupe 2
hotkey-description-controlgroupaddto03 = Ajouter au groupe 3
hotkey-description-controlgroupaddto04 = Ajouter au groupe 4
hotkey-description-controlgroupaddto05 = Ajouter au groupe 5
hotkey-description-controlgroupaddto06 = Ajouter au groupe 6
hotkey-description-controlgroupaddto07 = Ajouter au groupe 7
hotkey-description-controlgroupaddto08 = Ajouter au groupe 8
hotkey-description-controlgroupaddto09 = Ajouter au groupe 9
hotkey-description-controlgroupaddto10 = Ajouter au groupe 0
hotkey-description-controlgroupcombinewith01 = Combiner avec groupe 1
hotkey-description-controlgroupcombinewith02 = Combiner avec groupe 2
hotkey-description-controlgroupcombinewith03 = Combiner avec groupe 3
hotkey-description-controlgroupcombinewith04 = Combiner avec groupe 4
hotkey-description-controlgroupcombinewith05 = Combiner avec groupe 5
hotkey-description-controlgroupcombinewith06 = Combiner avec groupe 6
hotkey-description-controlgroupcombinewith07 = Combiner avec groupe 7
hotkey-description-controlgroupcombinewith08 = Combiner avec groupe 8
hotkey-description-controlgroupcombinewith09 = Combiner avec groupe 9
hotkey-description-controlgroupcombinewith10 = Combiner avec groupe 0
hotkey-description-controlgroupjumpto01 = Aller au groupe 1
hotkey-description-controlgroupjumpto02 = Aller au groupe 2
hotkey-description-controlgroupjumpto03 = Aller au groupe 3
hotkey-description-controlgroupjumpto04 = Aller au groupe 4
hotkey-description-controlgroupjumpto05 = Aller au groupe 5
hotkey-description-controlgroupjumpto06 = Aller au groupe 6
hotkey-description-controlgroupjumpto07 = Aller au groupe 7
hotkey-description-controlgroupjumpto08 = Aller au groupe 8
hotkey-description-controlgroupjumpto09 = Aller au groupe 9
hotkey-description-controlgroupjumpto10 = Aller au groupe 0
hotkey-description-removefromcontrolgroup = Retirer du groupe

## editor.yaml
hotkey-description-editorundo = Annuler
hotkey-description-editorredo = Rétablir
hotkey-description-editorcopy = Copier
hotkey-description-editorquicksave = Sauvegarder Carte
hotkey-description-editorpaste = Coller
hotkey-description-editordeleteselection = Supprimer Sélection
hotkey-description-editorselecttab = Onglet Sélection
hotkey-description-editortilestab = Onglet Tuiles
hotkey-description-editoroverlaystab = Onglet Calques
hotkey-description-editoractorstab = Onglet Acteurs
hotkey-description-editortoolstab = Onglet Outils
hotkey-description-editorhistorytab = Onglet Historique
hotkey-description-editorsettingstab = Onglet Paramètres
hotkey-description-editortogglegridoverlay = Calque Grille
hotkey-description-editortogglebuildableoverlay = Calque Terrain Constructible
hotkey-description-editortogglemarkeroverlay = Calque Repères

## game.yaml
hotkey-description-cyclebase = Aller à la Base
hotkey-description-tolastevent = Dernier Évènement Radar
hotkey-description-toselection = Aller à la Sélection
hotkey-description-selectallunits = Sélect. Unités de Combat
hotkey-description-selectunitsbytype = Sélectionner par Type
hotkey-description-cycleharvesters = Cycler Moissonneuses
hotkey-description-pause = Pause / Reprendre
hotkey-description-sell = Mode Vente
hotkey-description-repair = Mode Réparation
hotkey-description-placebeacon = Placer une Balise
hotkey-description-cyclestatusbars = Cycler Barres d'État
hotkey-description-togglemute = Basculer Muet
hotkey-description-toggleplayerstancecolor = Couleurs de Posture
hotkey-description-takescreenshot = Capture d'Écran
hotkey-description-attackmove = Déplacement Offensif
hotkey-description-stop = Arrêt
hotkey-description-scatter = Dispersion
hotkey-description-deploy = Déploiement
hotkey-description-guard = Garde
hotkey-description-stanceattackanything = Attaque Totale
hotkey-description-stancedefend = Défense
hotkey-description-stancereturnfire = Riposte
hotkey-description-stanceholdfire = Cessez-le-feu
hotkey-description-stopmusic = Arrêt
hotkey-description-pausemusic = Pause/Reprendre
hotkey-description-prevmusic = Précédent
hotkey-description-nextmusic = Suivant

## observer.yaml
hotkey-description-observercombinedview = Tous les Joueurs
hotkey-description-observerworldview = Désactiver Voile
hotkey-description-replayspeedslow = Vitesse Lente
hotkey-description-replayspeedregular = Vitesse Normale
hotkey-description-replayspeedfast = Vitesse Rapide
hotkey-description-replayspeedmax = Vitesse Maximale
hotkey-description-statisticsnone = Désactiver Stats
hotkey-description-statisticsbasic = Stats de Base
hotkey-description-statisticseconomy = Stats Économie
hotkey-description-statisticsproduction = Stats Production
hotkey-description-statisticssupportpowers = Stats Pouvoirs
hotkey-description-statisticscombat = Stats Combat
hotkey-description-statisticsarmy = Stats Armée
hotkey-description-statisticsgraph = Graphique Stats
hotkey-description-statisticsarmygraph = Graphique Valeur Armée

## production-common.yaml
hotkey-description-cycleproductionbuildings = Bâtiment Suivant
hotkey-description-selectproductionbuilding = Bâtiment Actuel
hotkey-description-production01 = Emplacement 01
hotkey-description-production02 = Emplacement 02
hotkey-description-production03 = Emplacement 03
hotkey-description-production04 = Emplacement 04
hotkey-description-production05 = Emplacement 05
hotkey-description-production06 = Emplacement 06
hotkey-description-production07 = Emplacement 07
hotkey-description-production08 = Emplacement 08
hotkey-description-production09 = Emplacement 09
hotkey-description-production10 = Emplacement 10
hotkey-description-production11 = Emplacement 11
hotkey-description-production12 = Emplacement 12
hotkey-description-production13 = Emplacement 13
hotkey-description-production14 = Emplacement 14
hotkey-description-production15 = Emplacement 15
hotkey-description-production16 = Emplacement 16
hotkey-description-production17 = Emplacement 17
hotkey-description-production18 = Emplacement 18
hotkey-description-production19 = Emplacement 19
hotkey-description-production20 = Emplacement 20
hotkey-description-production21 = Emplacement 21
hotkey-description-production22 = Emplacement 22
hotkey-description-production23 = Emplacement 23
hotkey-description-production24 = Emplacement 24

## supportpowers.yaml
hotkey-description-supportpower01 = Emplacement 01
hotkey-description-supportpower02 = Emplacement 02
hotkey-description-supportpower03 = Emplacement 03
hotkey-description-supportpower04 = Emplacement 04
hotkey-description-supportpower05 = Emplacement 05
hotkey-description-supportpower06 = Emplacement 06

## viewport.yaml
hotkey-description-mapscrollup = Défiler Haut
hotkey-description-mapscrolldown = Défiler Bas
hotkey-description-mapscrollleft = Défiler Gauche
hotkey-description-mapscrollright = Défiler Droite
hotkey-description-mapjumptotopedge = Aller en Haut
hotkey-description-mapjumptobottomedge = Aller en Bas
hotkey-description-mapjumptoleftedge = Aller à Gauche
hotkey-description-mapjumptorightedge = Aller à Droite
hotkey-description-mapbookmarksave01 = Enregistrer Repère 1
hotkey-description-mapbookmarkrestore01 = Aller au Repère 1
hotkey-description-mapbookmarksave02 = Enregistrer Repère 2
hotkey-description-mapbookmarkrestore02 = Aller au Repère 2
hotkey-description-mapbookmarksave03 = Enregistrer Repère 3
hotkey-description-mapbookmarkrestore03 = Aller au Repère 3
hotkey-description-mapbookmarksave04 = Enregistrer Repère 4
hotkey-description-mapbookmarkrestore04 = Aller au Repère 4
hotkey-description-zoomin = Zoom Avant
hotkey-description-zoomout = Zoom Arrière
hotkey-description-resetzoom = Réinitialiser Zoom
